# Generated by Django 4.1.3 on 2022-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=500)),
                ('BookQuantity', models.IntegerField()),
                ('BookGenre', models.CharField(max_length=500)),
                ('BookBestSeller', models.CharField(max_length=500)),
            ],
        ),
    ]
